// Generated by CoffeeScript 1.10.0
(function() {
  (function(clicked) {
    var currentpass, currentuser, pass, user;
    user = document.getElementById('username');
    pass = docuement.getElementById('password');
    currentuser = "robtest";
    currentpass = "1234";
    if (user === currentuser && pass === currentpass) {
      return window.alert("hello");
    }
  });

}).call(this);
