// Generated by CoffeeScript 1.10.0
this.goin = function() {
  var curruser, usernow;
  curruser = "robin";
  usernow = document.getElementsByClassName("gold-email-input").item(0);
  return usernow.value.color = "#ccc !important";
};
