// Generated by CoffeeScript 1.10.0
(function() {
  (function() {
    this.goin = function() {
      var currpass, curruser, email, password;
      curruser = 'robin';
      currpass = '123';
      email = void 0;
      password = void 0;
      email = document.loginform.elements['email'].value;
      password = document.loginform.elements['password'].value;
      if (email === curruser && password === currpass) {
        alert('successful');
      } else {
        alert('fail');
      }
    };
  }).call(this);

}).call(this);
